package engine

import (
	"github.com/google/uuid"
)

// newTicketID/newNodeID no longer exist here: ticket/node IDs are now minted
// by the store (see store.SQLiteRepository.CreateTicket/CreateNode) from a
// project's prefix and per-project/per-ticket sequence counters, not
// generated by the caller. Edge/artifact IDs are unaffected -- see
// domain.Project's doc comment / the execution plan's scope-out section --
// and keep their original opaque uuid-based scheme.
func shortUUID() string {
	return uuid.New().String()[:8]
}

func newEdgeID() string     { return "edge-" + shortUUID() }
func newArtifactID() string { return "art-" + shortUUID() }

// NewArtifactID is exported for callers (e.g. the HTTP layer's direct
// artifact-upload endpoint) that create artifacts without going through
// CompleteNode.
func NewArtifactID() string { return newArtifactID() }
